spring.application.name=scrum

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/teamdb
spring.data.mongodb.database=test

# Neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=test1234

# Redis
spring.redis.host=localhost
spring.redis.port=6379	

# Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=181161627304-llmclvl2fpib8i2qnhafnevl9vtq8upl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
